# This is a TOML configuration file.

# if set to true, allow running outside market open hours
#bypass_market_schedule = true

skip_existing = true
test_scanners = true

# ticket scanners, may have several
# scanners during the day
[scanners]
[scanners.GapDown]
filename = "scanners/gap_down.py"
target_strategy_name = "ShortGapDown"

# trading strategies, can have several *strategy* blocks
[strategies]
# strategy class name, must implement Strategy class
[strategies.ShortGapDown]
filename = "short_gap_down.py"

# check_patterns = true

# trading schedules block, trades many have
# several windows within the same day
[[strategies.ShortGapDown.schedule]]
duration = 60
start = 15
